---
abstract: 'Convenient hash tyng for time series data.'
author:
  - 'Takahiro Onodera <ong at garakuta.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tie-TimeSeries
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Search::Binary: 0
  Tie::Hash: 0
  perl: 5.006
version: 0.01
